services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: eye-of-lisary-backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - ../src:/app/src # Solo para desarrollo, permite Hot Reload
    deploy:
      resources:
        limits:
          memory: 2G # Los modelos de embedding consumen RAM
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: eye-of-lisary-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/chat
      - UPLOAD_URL=http://backend:8000/upload_sheet
    depends_on:
      backend:
        condition: service_healthy # Espera a que el healthcheck del backend pase
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped